services:
  node:
    build: .
    image: express-bookshelf-realworld
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - SECRET=${SECRET}
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/_coverage

  postgres:
    image: postgres:17.4
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
