// flow-typed signature: b5bd8fe5ad184a101af7c4a93d914203
// flow-typed version: <<STUB>>/bookshelf_v0.10.4/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bookshelf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bookshelf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bookshelf/bookshelf' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/base/collection' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/base/eager' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/base/events' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/base/model' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/base/promise' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/base/relation' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/bookshelf' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/collection' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/constants' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/eager' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/errors' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/extend' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/helpers' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/model' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/plugins/pagination' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/plugins/registry' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/plugins/virtuals' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/plugins/visibility' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/relation' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/sync' {
  declare module.exports: any;
}

declare module 'bookshelf/scripts/build' {
  declare module.exports: any;
}

declare module 'bookshelf/scripts/promise' {
  declare module.exports: any;
}

declare module 'bookshelf/src/base/collection' {
  declare module.exports: any;
}

declare module 'bookshelf/src/base/eager' {
  declare module.exports: any;
}

declare module 'bookshelf/src/base/events' {
  declare module.exports: any;
}

declare module 'bookshelf/src/base/model' {
  declare module.exports: any;
}

declare module 'bookshelf/src/base/promise' {
  declare module.exports: any;
}

declare module 'bookshelf/src/base/relation' {
  declare module.exports: any;
}

declare module 'bookshelf/src/bookshelf' {
  declare module.exports: any;
}

declare module 'bookshelf/src/collection' {
  declare module.exports: any;
}

declare module 'bookshelf/src/constants' {
  declare module.exports: any;
}

declare module 'bookshelf/src/eager' {
  declare module.exports: any;
}

declare module 'bookshelf/src/errors' {
  declare module.exports: any;
}

declare module 'bookshelf/src/extend' {
  declare module.exports: any;
}

declare module 'bookshelf/src/helpers' {
  declare module.exports: any;
}

declare module 'bookshelf/src/model' {
  declare module.exports: any;
}

declare module 'bookshelf/src/plugins/pagination' {
  declare module.exports: any;
}

declare module 'bookshelf/src/plugins/registry' {
  declare module.exports: any;
}

declare module 'bookshelf/src/plugins/virtuals' {
  declare module.exports: any;
}

declare module 'bookshelf/src/plugins/visibility' {
  declare module.exports: any;
}

declare module 'bookshelf/src/relation' {
  declare module.exports: any;
}

declare module 'bookshelf/src/sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bookshelf/bookshelf.js' {
  declare module.exports: $Exports<'bookshelf/bookshelf'>;
}
declare module 'bookshelf/lib/base/collection.js' {
  declare module.exports: $Exports<'bookshelf/lib/base/collection'>;
}
declare module 'bookshelf/lib/base/eager.js' {
  declare module.exports: $Exports<'bookshelf/lib/base/eager'>;
}
declare module 'bookshelf/lib/base/events.js' {
  declare module.exports: $Exports<'bookshelf/lib/base/events'>;
}
declare module 'bookshelf/lib/base/model.js' {
  declare module.exports: $Exports<'bookshelf/lib/base/model'>;
}
declare module 'bookshelf/lib/base/promise.js' {
  declare module.exports: $Exports<'bookshelf/lib/base/promise'>;
}
declare module 'bookshelf/lib/base/relation.js' {
  declare module.exports: $Exports<'bookshelf/lib/base/relation'>;
}
declare module 'bookshelf/lib/bookshelf.js' {
  declare module.exports: $Exports<'bookshelf/lib/bookshelf'>;
}
declare module 'bookshelf/lib/collection.js' {
  declare module.exports: $Exports<'bookshelf/lib/collection'>;
}
declare module 'bookshelf/lib/constants.js' {
  declare module.exports: $Exports<'bookshelf/lib/constants'>;
}
declare module 'bookshelf/lib/eager.js' {
  declare module.exports: $Exports<'bookshelf/lib/eager'>;
}
declare module 'bookshelf/lib/errors.js' {
  declare module.exports: $Exports<'bookshelf/lib/errors'>;
}
declare module 'bookshelf/lib/extend.js' {
  declare module.exports: $Exports<'bookshelf/lib/extend'>;
}
declare module 'bookshelf/lib/helpers.js' {
  declare module.exports: $Exports<'bookshelf/lib/helpers'>;
}
declare module 'bookshelf/lib/model.js' {
  declare module.exports: $Exports<'bookshelf/lib/model'>;
}
declare module 'bookshelf/lib/plugins/pagination.js' {
  declare module.exports: $Exports<'bookshelf/lib/plugins/pagination'>;
}
declare module 'bookshelf/lib/plugins/registry.js' {
  declare module.exports: $Exports<'bookshelf/lib/plugins/registry'>;
}
declare module 'bookshelf/lib/plugins/virtuals.js' {
  declare module.exports: $Exports<'bookshelf/lib/plugins/virtuals'>;
}
declare module 'bookshelf/lib/plugins/visibility.js' {
  declare module.exports: $Exports<'bookshelf/lib/plugins/visibility'>;
}
declare module 'bookshelf/lib/relation.js' {
  declare module.exports: $Exports<'bookshelf/lib/relation'>;
}
declare module 'bookshelf/lib/sync.js' {
  declare module.exports: $Exports<'bookshelf/lib/sync'>;
}
declare module 'bookshelf/scripts/build.js' {
  declare module.exports: $Exports<'bookshelf/scripts/build'>;
}
declare module 'bookshelf/scripts/promise.js' {
  declare module.exports: $Exports<'bookshelf/scripts/promise'>;
}
declare module 'bookshelf/src/base/collection.js' {
  declare module.exports: $Exports<'bookshelf/src/base/collection'>;
}
declare module 'bookshelf/src/base/eager.js' {
  declare module.exports: $Exports<'bookshelf/src/base/eager'>;
}
declare module 'bookshelf/src/base/events.js' {
  declare module.exports: $Exports<'bookshelf/src/base/events'>;
}
declare module 'bookshelf/src/base/model.js' {
  declare module.exports: $Exports<'bookshelf/src/base/model'>;
}
declare module 'bookshelf/src/base/promise.js' {
  declare module.exports: $Exports<'bookshelf/src/base/promise'>;
}
declare module 'bookshelf/src/base/relation.js' {
  declare module.exports: $Exports<'bookshelf/src/base/relation'>;
}
declare module 'bookshelf/src/bookshelf.js' {
  declare module.exports: $Exports<'bookshelf/src/bookshelf'>;
}
declare module 'bookshelf/src/collection.js' {
  declare module.exports: $Exports<'bookshelf/src/collection'>;
}
declare module 'bookshelf/src/constants.js' {
  declare module.exports: $Exports<'bookshelf/src/constants'>;
}
declare module 'bookshelf/src/eager.js' {
  declare module.exports: $Exports<'bookshelf/src/eager'>;
}
declare module 'bookshelf/src/errors.js' {
  declare module.exports: $Exports<'bookshelf/src/errors'>;
}
declare module 'bookshelf/src/extend.js' {
  declare module.exports: $Exports<'bookshelf/src/extend'>;
}
declare module 'bookshelf/src/helpers.js' {
  declare module.exports: $Exports<'bookshelf/src/helpers'>;
}
declare module 'bookshelf/src/model.js' {
  declare module.exports: $Exports<'bookshelf/src/model'>;
}
declare module 'bookshelf/src/plugins/pagination.js' {
  declare module.exports: $Exports<'bookshelf/src/plugins/pagination'>;
}
declare module 'bookshelf/src/plugins/registry.js' {
  declare module.exports: $Exports<'bookshelf/src/plugins/registry'>;
}
declare module 'bookshelf/src/plugins/virtuals.js' {
  declare module.exports: $Exports<'bookshelf/src/plugins/virtuals'>;
}
declare module 'bookshelf/src/plugins/visibility.js' {
  declare module.exports: $Exports<'bookshelf/src/plugins/visibility'>;
}
declare module 'bookshelf/src/relation.js' {
  declare module.exports: $Exports<'bookshelf/src/relation'>;
}
declare module 'bookshelf/src/sync.js' {
  declare module.exports: $Exports<'bookshelf/src/sync'>;
}
