// flow-typed signature: e1174d51ff2a20e501c5c5230e9e4335
// flow-typed version: <<STUB>>/checkit_v0.7.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'checkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'checkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'checkit/core' {
  declare module.exports: any;
}

declare module 'checkit/lang/en' {
  declare module.exports: any;
}

declare module 'checkit/lang/es' {
  declare module.exports: any;
}

declare module 'checkit/lang/fr' {
  declare module.exports: any;
}

declare module 'checkit/lang/ru' {
  declare module.exports: any;
}

declare module 'checkit/lodash-requires' {
  declare module.exports: any;
}

declare module 'checkit/test/assets/mocha' {
  declare module.exports: any;
}

declare module 'checkit/test/block' {
  declare module.exports: any;
}

declare module 'checkit/test/index' {
  declare module.exports: any;
}

declare module 'checkit/test/spec' {
  declare module.exports: any;
}

declare module 'checkit/test/sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'checkit/core.js' {
  declare module.exports: $Exports<'checkit/core'>;
}
declare module 'checkit/index' {
  declare module.exports: $Exports<'checkit'>;
}
declare module 'checkit/index.js' {
  declare module.exports: $Exports<'checkit'>;
}
declare module 'checkit/lang/en.js' {
  declare module.exports: $Exports<'checkit/lang/en'>;
}
declare module 'checkit/lang/es.js' {
  declare module.exports: $Exports<'checkit/lang/es'>;
}
declare module 'checkit/lang/fr.js' {
  declare module.exports: $Exports<'checkit/lang/fr'>;
}
declare module 'checkit/lang/ru.js' {
  declare module.exports: $Exports<'checkit/lang/ru'>;
}
declare module 'checkit/lodash-requires.js' {
  declare module.exports: $Exports<'checkit/lodash-requires'>;
}
declare module 'checkit/test/assets/mocha.js' {
  declare module.exports: $Exports<'checkit/test/assets/mocha'>;
}
declare module 'checkit/test/block.js' {
  declare module.exports: $Exports<'checkit/test/block'>;
}
declare module 'checkit/test/index.js' {
  declare module.exports: $Exports<'checkit/test/index'>;
}
declare module 'checkit/test/spec.js' {
  declare module.exports: $Exports<'checkit/test/spec'>;
}
declare module 'checkit/test/sync.js' {
  declare module.exports: $Exports<'checkit/test/sync'>;
}
