// flow-typed signature: b501b7607103a9ed49cddc16ffe8bdde
// flow-typed version: <<STUB>>/express-jwt_v5.3.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-jwt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-jwt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-jwt/lib/errors/UnauthorizedError' {
  declare module.exports: any;
}

declare module 'express-jwt/lib/index' {
  declare module.exports: any;
}

declare module 'express-jwt/test/jwt.test' {
  declare module.exports: any;
}

declare module 'express-jwt/test/multitenancy.test' {
  declare module.exports: any;
}

declare module 'express-jwt/test/revocation.test' {
  declare module.exports: any;
}

declare module 'express-jwt/test/string_token.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-jwt/lib/errors/UnauthorizedError.js' {
  declare module.exports: $Exports<'express-jwt/lib/errors/UnauthorizedError'>;
}
declare module 'express-jwt/lib/index.js' {
  declare module.exports: $Exports<'express-jwt/lib/index'>;
}
declare module 'express-jwt/test/jwt.test.js' {
  declare module.exports: $Exports<'express-jwt/test/jwt.test'>;
}
declare module 'express-jwt/test/multitenancy.test.js' {
  declare module.exports: $Exports<'express-jwt/test/multitenancy.test'>;
}
declare module 'express-jwt/test/revocation.test.js' {
  declare module.exports: $Exports<'express-jwt/test/revocation.test'>;
}
declare module 'express-jwt/test/string_token.test.js' {
  declare module.exports: $Exports<'express-jwt/test/string_token.test'>;
}
