// flow-typed signature: d0f797fa303d30cbe3019fc39782d40e
// flow-typed version: <<STUB>>/passport-local_v1.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-local'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-local' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-local/lib/index' {
  declare module.exports: any;
}

declare module 'passport-local/lib/strategy' {
  declare module.exports: any;
}

declare module 'passport-local/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-local/lib/index.js' {
  declare module.exports: $Exports<'passport-local/lib/index'>;
}
declare module 'passport-local/lib/strategy.js' {
  declare module.exports: $Exports<'passport-local/lib/strategy'>;
}
declare module 'passport-local/lib/utils.js' {
  declare module.exports: $Exports<'passport-local/lib/utils'>;
}
