// flow-typed signature: 1dba66162e323091096aa9e4e073a25f
// flow-typed version: <<STUB>>/pg_v7.3.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pg/lib/client' {
  declare module.exports: any;
}

declare module 'pg/lib/connection-parameters' {
  declare module.exports: any;
}

declare module 'pg/lib/connection' {
  declare module.exports: any;
}

declare module 'pg/lib/defaults' {
  declare module.exports: any;
}

declare module 'pg/lib/index' {
  declare module.exports: any;
}

declare module 'pg/lib/native/client' {
  declare module.exports: any;
}

declare module 'pg/lib/native/index' {
  declare module.exports: any;
}

declare module 'pg/lib/native/query' {
  declare module.exports: any;
}

declare module 'pg/lib/query' {
  declare module.exports: any;
}

declare module 'pg/lib/result' {
  declare module.exports: any;
}

declare module 'pg/lib/type-overrides' {
  declare module.exports: any;
}

declare module 'pg/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pg/lib/client.js' {
  declare module.exports: $Exports<'pg/lib/client'>;
}
declare module 'pg/lib/connection-parameters.js' {
  declare module.exports: $Exports<'pg/lib/connection-parameters'>;
}
declare module 'pg/lib/connection.js' {
  declare module.exports: $Exports<'pg/lib/connection'>;
}
declare module 'pg/lib/defaults.js' {
  declare module.exports: $Exports<'pg/lib/defaults'>;
}
declare module 'pg/lib/index.js' {
  declare module.exports: $Exports<'pg/lib/index'>;
}
declare module 'pg/lib/native/client.js' {
  declare module.exports: $Exports<'pg/lib/native/client'>;
}
declare module 'pg/lib/native/index.js' {
  declare module.exports: $Exports<'pg/lib/native/index'>;
}
declare module 'pg/lib/native/query.js' {
  declare module.exports: $Exports<'pg/lib/native/query'>;
}
declare module 'pg/lib/query.js' {
  declare module.exports: $Exports<'pg/lib/query'>;
}
declare module 'pg/lib/result.js' {
  declare module.exports: $Exports<'pg/lib/result'>;
}
declare module 'pg/lib/type-overrides.js' {
  declare module.exports: $Exports<'pg/lib/type-overrides'>;
}
declare module 'pg/lib/utils.js' {
  declare module.exports: $Exports<'pg/lib/utils'>;
}
